modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/spoorn/SpoornWeaponAttributes/issues"
license = "MIT"

[[mods]]
modId = "spoornweaponattributes"
version = "${version}"
displayName = "Spoorn Weapon Attributes"
authors = "spoorn"
description = '''
Adds randomized weapon attributes
'''
#logoFile = ""

[[mixins]]
config = "spoornweaponattributes-common.mixins.json"

[[dependencies.spoornweaponattributes]]
modId = "neoforge"
mandatory = true
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spoornweaponattributes]]
modId = "minecraft"
mandatory = true
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spoornweaponattributes]]
modId = "cloth_config"
mandatory = true
versionRange = "[26.2,)"
ordering = "NONE"
side = "CLIENT"
